language: php
dist: bionic
php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - CORE_BRANCH=master
  matrix:
  - DB=sqlite

branches:
  only:
    - master

before_install:
  - nvm install 8.15
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh twofactor_backup_codes $CORE_BRANCH $DB
  - make
  - make appstore
  - cd ../core
  - composer install
  - bash ./core_install.sh $DB
  - php occ app:enable twofactor_backup_codes

script:
  # execute unit tests
  - cd apps/twofactor_backup_codes/tests
  - ../../../lib/composer/phpunit/phpunit/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)


after_failure:
    - cat ../../data/owncloud.log

matrix:
  include:
    - php: 7.3
      services: mysql
      env: DB=mysql CORE_BRANCH=master
    - php: 7.3
      services: postgresql
      env: DB=pgsql CORE_BRANCH=master

  fast_finish: true

